export const trendingEvents = [
  {
    id: "1",
    title: "Sample Hackathon 2025",
    description: "This is a demo hackathon event to showcase the event portal features. Not a real event.",
    type: "Hackathon",
    mode: "Offline",
    date: "March 15-17, 2025",
    location: "Demo Location",
    participants: "50+",
    prize: "$1,000",
    image: "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=400&h=200&fit=crop",
    organizer: "Demo Organizer",
    website: "#",
    deadline: "2025-03-10",
    domain: "Web Development"
  },
  {
    id: "2",
    title: "Sample Internship Program",
    description: "This is a demo internship event to showcase the event portal features. Not a real opportunity.",
    type: "Internship",
    mode: "Offline",
    date: "Applications Open",
    location: "Demo Company",
    participants: "20",
    prize: "Stipend",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=200&fit=crop",
    organizer: "Demo Company",
    website: "#",
    deadline: "2025-01-15",
    domain: "Software Engineering"
  },
  {
    id: "3",
    title: "Sample Tech Symposium",
    description: "This is a demo tech symposium to showcase the event portal features. Not a real event.",
    type: "Festival",
    mode: "Offline",
    date: "April 5-7, 2025",
    location: "Demo Venue",
    participants: "200+",
    prize: "Certificates",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=200&fit=crop",
    organizer: "Demo Tech Club",
    website: "#",
    deadline: "2025-03-25",
    domain: "Technology"
  },
  {
    id: "4",
    title: "Sample Programming Contest",
    description: "This is a demo programming contest to showcase the event portal features. Not a real competition.",
    type: "Competition",
    mode: "Online",
    date: "May 10, 2025",
    location: "Online",
    participants: "100+",
    prize: "$500",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=200&fit=crop",
    organizer: "Demo Programming Club",
    website: "#",
    deadline: "2025-05-05",
    domain: "Algorithms"
  },
  {
    id: "5",
    title: "Sample Web Development Workshop",
    description: "This is a demo workshop to showcase the event portal features. Not a real workshop.",
    type: "Workshop",
    mode: "Offline",
    date: "June 20, 2025",
    location: "Demo Lab",
    participants: "30",
    prize: "Certificates",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=200&fit=crop",
    organizer: "Demo Web Club",
    website: "#",
    deadline: "2025-06-15",
    domain: "Web Development"
  },
  {
    id: "6",
    title: "Sample Data Science Workshop",
    description: "This is a demo workshop to showcase the event portal features. Not a real workshop.",
    type: "Workshop",
    mode: "Offline",
    date: "July 5, 2025",
    location: "Demo Lab",
    participants: "25",
    prize: "Certificates",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=200&fit=crop",
    organizer: "Demo Data Club",
    website: "#",
    deadline: "2025-06-30",
    domain: "Data Science"
  }
];